/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'wiki-pages': WikiPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'wiki-pages': WikiPagesSelect<false> | WikiPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-pages".
 */
export interface WikiPage {
  id: number;
  title: string;
  section: 'Wiki' | 'Project' | 'Wet Lab' | 'Dry Lab' | 'Hardware' | 'Beyond the Bench' | 'Team' | 'Safety';
  /**
   * Use a Gatsby/iGEM route like /cms-test/. Start and end with a slash.
   */
  path: string;
  navTitle: string;
  order: number;
  description: string;
  owners: {
    name: string;
    id?: string | null;
  }[];
  updated: string;
  content: (
    | {
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        title?: string | null;
        tone?: ('note' | 'success' | 'warning') | null;
        body: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callout';
      }
    | {
        /**
         * Upload or choose a Payload media item. Export copies it into Gatsby static files.
         */
        image?: (number | null) | Media;
        /**
         * Optional fallback for existing static paths such as /images/example.png. Prefer Media above.
         */
        src?: string | null;
        alt: string;
        caption?: string | null;
        /**
         * Optional photo credit shown below the caption.
         */
        credit?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'figure';
      }
    | {
        figures: {
          /**
           * Upload or choose a Payload media item. Export copies it into Gatsby static files.
           */
          image?: (number | null) | Media;
          /**
           * Optional fallback for existing static paths such as /images/example.png. Prefer Media above.
           */
          src?: string | null;
          alt: string;
          caption?: string | null;
          /**
           * Optional photo credit shown below the caption.
           */
          credit?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageGrid';
      }
    | {
        caption?: string | null;
        /**
         * GitHub-flavored markdown table (header row, separator, data rows). Example:
         * | Col A | Col B |
         * | --- | --- |
         * | a | b |
         */
        tableMarkdown: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dataTable';
      }
    | {
        /**
         * Optional heading shown above the contribution calendar.
         */
        title?: string | null;
        /**
         * Optional caption shown below the contribution calendar.
         */
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contributionCalendar';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'hardwareArchitectureDiagram';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'designSketchbook';
      }
    | {
        layout?: ('horizontal' | 'side') | null;
        /**
         * Optional tab id to open first, e.g. progress.
         */
        defaultTab?: string | null;
        tabs: {
          /**
           * Stable id using letters, numbers, hyphens, or underscores.
           */
          id: string;
          label: string;
          /**
           * Markdown content for this tab. MDX components can be used if needed.
           */
          body: string;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'pageTabs';
      }
    | {
        /**
         * Which approved interactive component to render.
         */
        gizmo: 'growthCurve' | 'hardwareNotebook' | 'contributionTimeline' | 'bioreactorRequirements';
        /**
         * Optional heading shown above the gizmo.
         */
        title?: string | null;
        /**
         * Optional settings passed to the gizmo as props, e.g. { "growthRate": 0.5, "carryingCapacity": 200 }. Leave blank to use defaults.
         */
        config?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Optional caption shown below the gizmo.
         */
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'interactiveGizmo';
      }
    | {
        /**
         * Escape hatch for web members when a visual block is not enough. Prefer the blocks above.
         */
        body: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'markdown';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'wiki-pages';
        value: number | WikiPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-pages_select".
 */
export interface WikiPagesSelect<T extends boolean = true> {
  title?: T;
  section?: T;
  path?: T;
  navTitle?: T;
  order?: T;
  description?: T;
  owners?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updated?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              title?: T;
              tone?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        figure?:
          | T
          | {
              image?: T;
              src?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              figures?:
                | T
                | {
                    image?: T;
                    src?: T;
                    alt?: T;
                    caption?: T;
                    credit?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dataTable?:
          | T
          | {
              caption?: T;
              tableMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        contributionCalendar?:
          | T
          | {
              title?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        hardwareArchitectureDiagram?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        designSketchbook?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        pageTabs?:
          | T
          | {
              layout?: T;
              defaultTab?: T;
              tabs?:
                | T
                | {
                    id?: T;
                    label?: T;
                    body?: T;
                  };
              id?: T;
              blockName?: T;
            };
        interactiveGizmo?:
          | T
          | {
              gizmo?: T;
              title?: T;
              config?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        markdown?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}